services:

  golang:
    image: golang:1.22
    container_name: "${COMPOSE_PROJECT_NAME}-golang"
    working_dir: /app
    environment:
      DB_NAME: migrate
      DB_USER: migrate
      DB_PASSWORD: migrate
      DB_HOST: sqlite
      DB_PORT: 3306
      DB_TYPE: sqlite
      DB_TABLE: migrations
      MIGRATION_PATH: migrations/data
    volumes:
      - .:/app
    command: sh -c "go mod tidy && go build -o migrate main.go && tail -f /dev/null"

#   mysql:
#     image: mysql:5.7
#     container_name: "${COMPOSE_PROJECT_NAME}-mysql"
#     environment:
#       MYSQL_ROOT_PASSWORD: migrate
#       MYSQL_DATABASE: migrate
#       MYSQL_USER: migrate
#       MYSQL_PASSWORD: migrate
#     volumes:
#       - mysql_data:/var/lib/mysql
#
#   postgres:
#     image: postgres:16-alpine
#     container_name: "${COMPOSE_PROJECT_NAME}-postgres"
#     ports:
#       - 5432:5432
#     volumes:
#       - postgres_data:/data/postgres
#     environment:
#       - POSTGRES_PASSWORD=migrate
#       - POSTGRES_USER=migrate
#       - POSTGRES_DB=migrate
#
# volumes:
#   mysql_data:
#   postgres_data:
