# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DB_NAME: migrations
      DB_TABLE: migrations
      MIGRATION_PATH: migrations/data
      DB_TYPE: sqlite
      
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
